# Generated by Django 3.2.4 on 2021-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsMini',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('department', models.TextField(db_column='Department')),
                ('specializedfield', models.TextField(db_column='SpecializedField')),
            ],
            options={
                'db_table': 'doctors_mini',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
