# Generated by Django 3.2.4 on 2021-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210623_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatholicDoc',
            fields=[
                ('id', models.TextField(db_column='Id', primary_key=True, serialize=False)),
                ('department', models.TextField(db_column='Department')),
                ('specializedfield', models.TextField(db_column='SpecializedField')),
                ('career', models.TextField(db_column='Career')),
                ('education', models.TextField(db_column='Education')),
                ('numofthesis', models.TextField(db_column='NumofThesis')),
                ('nameofthesis', models.TextField(db_column='NameofThesis')),
            ],
            options={
                'db_table': 'catholic_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeoulDoc',
            fields=[
                ('id', models.TextField(db_column='Id', primary_key=True, serialize=False)),
                ('department', models.TextField(db_column='Department')),
                ('specializedfield', models.TextField(db_column='SpecializedField')),
                ('career', models.TextField(db_column='Career')),
                ('education', models.TextField(db_column='Education')),
                ('numofthesis', models.TextField(db_column='NumofThesis')),
                ('nameofthesis', models.TextField(db_column='NameofThesis')),
            ],
            options={
                'db_table': 'seoul_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkkuDoc',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=45, primary_key=True, serialize=False)),
                ('department', models.CharField(db_column='Department', max_length=45)),
                ('specializedfield', models.CharField(db_column='SpecializedField', max_length=255)),
                ('career', models.TextField(db_column='Career')),
                ('education', models.TextField(db_column='Education')),
                ('numofthesis', models.CharField(db_column='NumofThesis', max_length=15)),
                ('nameofthesis', models.TextField(db_column='NameofThesis')),
            ],
            options={
                'db_table': 'skku_doc',
                'managed': False,
            },
        ),
    ]
